### ISSUE TITLE
OSError on backend when running cypress. Plone 5.2.2

### ISSUE THREAD

**Issue by avoinea** [plone/volto#1788]
```
OSError: cannot identify image file <_io.FileIO name='/tmp/tmp5j8al09n.demoblobs/0x0b/0xd9/0x64/0x4b/0xaa/0x7c/0xca/0xb5/0x03da619ca94070dd.blob' mode='rb' closefd=True>
ERROR:kitconcept.volto.scaling:Could not scale "<plone.namedfile.file.NamedBlobImage object at 0x7fd48924aeb0 oid 0xbd9644baa7ccab2 in <Connection at 7fd473948f10>>" of 'http://localhost:55001/plone/image.png'
Traceback (most recent call last):
  File "/joint/buildout/eggs/kitconcept.volto-1.4.0-py3.8.egg/kitconcept/volto/scaling.py", line 78, in __call__
    result = self.create_scale(
  File "/joint/buildout/eggs/kitconcept.volto-1.4.0-py3.8.egg/kitconcept/volto/scaling.py", line 31, in create_scale
    return scaleImage(
  File "/joint/buildout/eggs/plone.scale-3.1.1-py3.8.egg/plone/scale/scale.py", line 57, in scaleImage
    image = PIL.Image.open(image)
  File "/joint/buildout/eggs/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.FileIO name='/tmp/tmp5j8al09n.demoblobs/0x0b/0xd9/0x64/0x4b/0xaa/0x7c/0xca/0xb5/0x03da619ca94070dd.blob' mode='rb' closefd=True>
```

**Comment by tisto** [comment]
@avoinea I saw those as well. Can you pls add some steps to reproduce?

**Comment by tiberiuichim** [comment]
Maybe related to this? https://github.com/plone/volto/issues/1704

**Comment by tiberiuichim** [comment]
Probably closed by https://github.com/plone/volto/pull/1823

The tests never failed for files uploaded with Cypress because the file content was never checked. The image scaling code complained.

**Comment by sneridagh** [comment]
@avoinea can we close this?
