### ISSUE TITLE
Please update documentation of how to use sass in a project.

### ISSUE THREAD

**Issue by ksuess** [plone/volto#2040]
Documentation: "Use sass loader": https://docs.voltocms.com/theming/using-third-party-themes/#use-sass-loader

An update with a working example for a simple project would be great.  Thank you!

**Comment by tiberiuichim** [comment]
@ksuess This is what we use for scss: https://github.com/eea/volto-searchkit/blob/master/razzle.extend.js

**Comment by ksuess** [comment]
@tiberiuichim 
I know it's a busy time. But I am curious. Am I missing again an upgrade task or what do I miss to configure?
A volto app with add-on eea.volto-searchkit is throwing:

```
yarn start
yarn run v1.22.10
$ razzle start
plugins [
  { object: { modifyWebpackConfig: [Function: modifyWebpackConfig] } },
  { object: { modifyWebpackConfig: [Function: modifyWebpackConfig] } },
  { object: { modifyWebpackConfig: [Function: modifyWebpackConfig] } },
  { object: { modifyWebpackConfig: [Function: modifyWebpackConfig] } },
  { object: { modifyJestConfig: [Function: modifyJestConfig] } }
]
(node:67866) UnhandledPromiseRejectionWarning: Error: Cannot find module 'razzle-plugin-scss' from '/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config'
    at Function.resolveSync [as sync] (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/resolve/lib/sync.js:89:15)
    at loadPlugin (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadPlugins.js:28:40)
    at loadPlugin (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadPlugins.js:8:12)
    at /Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadPlugins.js:40:12
    at Array.map (<anonymous>)
    at loadPlugins (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadPlugins.js:39:18)
    at /Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadRazzleConfig.js:44:9
    at new Promise (<anonymous>)
    at module.exports (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/config/loadRazzleConfig.js:12:10)
    at /Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/scripts/start.js:38:5
    at new Promise (<anonymous>)
    at main (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/scripts/start.js:37:10)
    at Object.<anonymous> (/Users/ksuess/PloneDeployments/deployigib/work/voltoapp/node_modules/razzle/scripts/start.js:176:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
(node:67866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
✨  Done in 4.51s.

```

**Comment by tiberiuichim** [comment]
Yeah, it looks like poor dependency management from volto-searchkit. I'll add razzle-plugin-scss as a dependency, though take volto-searchkit just as an example, it's not something that's really usable right now.

**Comment by tiberiuichim** [comment]
@ksuess Nope, volto-searchkit had razzle-plugin-scss as a dependency. Maybe you need to add src/addons/volto-searchkit as a workspace? 

You need to either install the volto-searchkit addon as a real JS package (`yarn add -W eea/volto-searchkit`) inside your Volto project, or add the addon to the yarn workspaces. yarn workspaces are meant to "lift" the dependencies of *development* addons to the main node_modules
