### ISSUE TITLE
Volto master fails with "TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by tisto** [plone/volto#2447]
**Describe the bug**

Running Volto leads to the following traceback:

````
TypeError: Cannot read property 'replace' of undefined
    at p.render (/Users/timo/workspace/plone/volto/build/server.js:1:369209)
    at d (/Users/timo/workspace/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/Users/timo/workspace/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/timo/workspace/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/timo/workspace/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/timo/workspace/plone/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /Users/timo/workspace/plone/volto/build/server.js:1:103183
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
````

**To Reproduce**

1. Checkout Volto master
2. make build-frontend´
3. make start-frontend
4. Access localhost:3000
5. -> Error Trace

**Software (please complete the following information):**
 - OS: OS X 11.3.1 (Macbook Pro M1)
 - Volto Version 13.x (master)

**Comment by tisto** [comment]
@sneridagh I just checked this with Volto 12.14.0 and it works. When I move to the first 13 alpha (13.0.0-alpha.0) it breaks. It seems that something in that release breaks the M1 (https://github.com/plone/volto/blob/master/CHANGELOG.md#1300-alpha0-2021-05-03).

**Comment by tisto** [comment]
@iFlameing @jackahl can you please check the latest Volto master and let me know if that breaks for you as well?

**Comment by sneridagh** [comment]
```
start-frontend: dist
	yarn start:prod
```

This starts the previously compiled build for convenience, in Volto 13, a compiled build should always have an env var pointing to the right server.

**Comment by nileshgulia1** [comment]
I cannot replicate this in my Macbook M1 machine.
