### ISSUE TITLE
passwordreset raises TypeError: Cannot read property 'replace' of undefined in Anontools.jsx

### ISSUE THREAD

**Issue by oggers** [plone/volto#2719]
Hi all,

When I want to reset the password through volto, I request it and receive the email with the correct url (frontend_domian from kitconcept/volto is configured correctly), but when I open the received url it raises the given error.

Backtrace production:

```
yarn run v1.22.5
$ NODE_ENV=production node build/server.js
API server (API_PATH) is set to: https://www.example.com/api
🎭 Volto started at http://localhost:3010 🚀
TypeError: Cannot read property 'replace' of undefined
    at p.render (/usr/local/volto/build/server.js:1:416005)
    at d (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /usr/local/volto/build/server.js:1:121281
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Backtrace development:

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
✅  Server-side HMR Enabled!
Volto is running in SEAMLESS mode
Using internal proxy: http://localhost:3000 -> http://localhost:5080/Plone
🎭 Volto started at http://localhost:3000 🚀
TypeError: Cannot read property 'replace' of undefined
    at Anontools.render (/usr/local/volto/node_modules/@plone/volto/src/components/theme/Anontools/Anontools.jsx:57:1)
    at processChild (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/usr/local/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at /usr/local/volto/build/webpack:/node_modules/@plone/volto/src/server.jsx:202:1
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I have tested it with volto 13.15.1 and 12.14.2 without success, and the same happens in development mode.

Anyone have this problem????

**Comment by davisagli** [comment]
The line from this error was replaced in https://github.com/plone/volto/pull/4845
