### ISSUE TITLE
loginRenew: Cannot read property 'locationBeforeTransitions' of undefined

### ISSUE THREAD

**Issue by bloodbare** [plone/volto#273]
With a volto instance runnig, at loginRenew time this exception happens,

Backend: Guillotina

```/Users/ramon/floss/volto/src/helpers/AuthToken/AuthToken.js:54
              store.dispatch(loginRenew());
^

TypeError: Cannot read property 'locationBeforeTransitions' of undefined

  52 |               new Date().getTime()
  53 |             ) {
> 54 |               store.dispatch(loginRenew());
  55 |             } else {
  56 |               // Logout
  57 |               Router.push(

    at Timeout._onTimeout (/Users/ramon/floss/volto/src/helpers/AuthToken/AuthToken.js:54:1)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by sneridagh** [comment]
Fixed
