### ISSUE TITLE
Problem when component shadowing App.jsx

### ISSUE THREAD

**Issue by jimbiscuit** [plone/volto#2835]
When trying to component shadowing App.jsx I got this error

**Traceback**

```
Cannot find module '../MultilingualRedirector/MultilingualRedirector'

  91239 | /* harmony import */ var _plone_volto_icons_clear_svg__WEBPACK_IMPORTED_MODULE_21__ = __webpack_require__(/*! @plone/volto/icons/clear.svg */ "./node_modules/@plone/volto/src/icons/clear.svg");
  91240 | /* harmony import */ var _plone_volto_icons_clear_svg__WEBPACK_IMPORTED_MODULE_21___default = /*#__PURE__*/__webpack_require__.n(_plone_volto_icons_clear_svg__WEBPACK_IMPORTED_MODULE_21__);
> 91241 | !(function webpackMissingModule() { var e = new Error("Cannot find module '../MultilingualRedirector/MultilingualRedirector'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
  91242 | !(function webpackMissingModule() { var e = new Error("Cannot find module '../../manage/WorkingCopyToastsFactory/WorkingCopyToastsFactory'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
  91243 | !(function webpackMissingModule() { var e = new Error("Cannot find module '../../manage/LockingToastsFactory/LockingToastsFactory'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
  91244 | /* harmony import */ var _sentry_browser__WEBPACK_IMPORTED_MODULE_23__ = __webpack_require__(/*! @sentry/browser */ "@sentry/browser");

    at webpackMissingModule (/Users/jchandelle/workspace/website/website-frontend/build/server.js:91241:45)
    at Module../src/customizations/components/theme/App/App.jsx (/Users/jchandelle/workspace/website/website-frontend/build/server.js:91241:168)
    at __webpack_require__ (/Users/jchandelle/workspace/website/website-frontend/webpack/bootstrap:754:1)
    at fn (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/components/index.js (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/node_modules/@plone/volto/src/components/index.js:1:1)
    at __webpack_require__ (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/components/manage/Widgets/AlignWidget.jsx (/Users/jchandelle/workspace/website/website-frontend/build/server.js:44496:81)
    at __webpack_require__ (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/jchandelle/workspace/website/website-frontend/build/webpack:/webpack/bootstrap:59:1)
```

**Software:**
 - OS: MacOS 10.15.7
 - Browser: Firefox 94.0
 - Volto Version [e.g. 8.5.0] : 14.0.0-alpha.26
 - Plone Version [e.g. 5.2.2]  : 6.0.0a1
 - Plone REST API Version [e.g. 7.0.1] : 8.12.1

**Comment by tiberiuichim** [comment]
This might be a bit harder to pull, but I think we could adjust the relative resolver to detect if the module is in customizations.
