### ISSUE TITLE
'Cannot set headers after they are sent to the client' when user logged and Volto try to user loginRenew

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#2839]
When you are loggedin in Volto, and periodically Volto try to renew the login, an error 
'Cannot set headers after they are sent to the client'
is throw

**Comment by tiberiuichim** [comment]
@giuliaghisini Do you have a traceback? It would help with the hunt for this bug.

**Comment by giuliaghisini** [comment]
@tiberiuichim this is the traceback

```

(node:88518) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:264:10)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:158:21)
    at /Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/volto-middleware-static/src/index.js:43:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:88518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:88518) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:158:21)
    at /Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/volto-middleware-static/src/index.js:43:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:88518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:88518) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:158:21)
    at /Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/volto-middleware-static/src/index.js:43:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:88518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:88518) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:158:21)
    at /Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/volto-middleware-static/src/index.js:43:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:88518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:88518) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at /Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/http-proxy-middleware/dist/handlers/response-interceptor.js:80:22
    at Array.forEach (<anonymous>)
    at copyHeaders (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/http-proxy-middleware/dist/handlers/response-interceptor.js:73:14)
    at IncomingMessage.<anonymous> (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/http-proxy-middleware/dist/handlers/response-interceptor.js:22:13)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:88518) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
```

**Comment by tiberiuichim** [comment]
Seems to be something coming from volto-middleware-static ? Indeed, some pecularities might have been introduced by recent changes to how the express middlewares are executed.

To me this looks dubious: https://github.com/collective/volto-middleware-static/blob/e9580eacd94145d1427f9d168227d417a6850ec0/src/index.js#L48

I'd expect a return after `getResource`, and not execute the next middlewares.

**Comment by tiberiuichim** [comment]
Caveat: I'm not an nodejs express developer, I might be wrong.

**Comment by giuliaghisini** [comment]
that was one error (because in my project i'm using static resources.

This is the problem with loginRenew, and it seems to be similar:

```
[React Intl] Missing locale data for locale: "it". Using default locale: "en" as fallback.
(node:14287) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:771:10)
    at ServerResponse.header (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/express/lib/response.js:774:12)
    at errorHandler (/Users/giuliaghisini/progetti/io-visit/volto-iovisit/node_modules/@plone/volto/src/server.jsx:118:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:14287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
```

**Comment by tiberiuichim** [comment]
@giuliaghisini Do you have some suggestions on how I can reproduce this problem?

**Comment by giuliaghisini** [comment]
> @giuliaghisini Do you have some suggestions on how I can reproduce this problem?

yes, simply start a Volto application
then login
and wait until volto do loginRenew

**Comment by sneridagh** [comment]
I also stumbled upon it a few times... some reproducible, some others don't... The bad thing is that the node server breaks completely...

Setting the cache headers here if error, is strictly necessary? I guess that the most easy way is removing it for now.

@tiberiuichim @giuliaghisini ?

**Comment by giuliaghisini** [comment]
what are those headers for? to communicate with Plone?
I think it is necessary to check these cases well: 

- change of language
- edit of contents in babel view
- authenticated users edit/add.. 
and all cases for which headers are sent to the server..

**Comment by nileshgulia1** [comment]
I'm also starting to experience this error in volto 14 projects. My first thought was maybe some middleware injecting headers after the request.
