### ISSUE TITLE
TypeError: _plone_volto_config__WEBPACK_IMPORTED_MODULE_1__.addonRoutes is not iterable

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#3228]
**Describe the bug**

Error starting server:

```bash
$ yarn start
yarn run v1.22.17
$ razzle start
 WAIT  Compiling...


✖ Client
  Compiled with some errors in 18.34s

◯ Server
  

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

✖ Client
  Compiled with some errors in 568.36ms

● Server █████████████████████████ building (35%) 212/242 modules 30 active
 ...4m› node_modules/@plone/volto/src/components/theme/Forbidden/Forbidden.jsx


✖ Client
  Compiled with some errors in 568.36ms

✖ Server
  Compiled with some errors in 3.28s


/home/user/my-volto-app/src/config.js:40
export const addonRoutes = [...defaultAddonRoutes];
^

TypeError: _plone_volto_config__WEBPACK_IMPORTED_MODULE_1__.addonRoutes is not iterable

  38 | };
  39 | 
> 40 | export const addonRoutes = [...defaultAddonRoutes];
  41 | export const addonReducers = { ...defaultAddonReducers };
  42 | 

    at Module../src/config.js (/home/user/my-volto-app/src/config.js:40:1)
    at __webpack_require__ (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:754:1)
    at fn (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:59:1)
    at Module.../../../../tmp/tmp-7428-Ad06lFKARKjl-.js (/home/user/my-volto-app/build/webpack:/tmp/tmp-7428-Ad06lFKARKjl-.js:6:1)
    at __webpack_require__ (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:754:1)
    at fn (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/config/index.js (/home/user/my-volto-app/build/server.js:56213:76)
    at __webpack_require__ (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:754:1)
    at fn (/home/user/my-volto-app/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/server.jsx (/home/user/my-volto-app/build/server.js:69056:77)

```

**To Reproduce**

```bash
$ npx @plone/create-volto-app my-volto-app
$ cd my-volto-app
$ yarn start
```

**Expected behavior**
The server start

**Screenshots**

**Software (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Chrome
- Volto Version 15.3.0
- Plone Version 6.0a3
- Plone REST API Version 8.21.0

**Comment by wesleybl** [comment]
I was creating the `Volto` project according to the [current training.plone.org documentation](https://github.com/plone/training/blob/e66e59648b0292a19527bcc8f6d0b217bb8aa010/docs/react/bootstrap.md#bootstrapping-a-project). This is:

```
npx @plone/create-volto-app my-volto-app
```

But this documentation is outdated. Look:

https://github.com/plone/training/issues/563

Using [current Volto documentation](https://github.com/plone/volto/blob/728a818feeca83805b1f06f1d90d4b19c6c55eb2/README.md#create-a-volto-project-using-the-generator), it works:

```
npm install -g yo @plone/generator-volto
yo @plone/volto
```
