### ISSUE TITLE
Storybook build fails in `plone/documentation`

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3688]
See error log from build job in `plone/documentation`

https://github.com/plone/documentation/actions/runs/3141183181/jobs/5103412176

A proposed solution is in the docs for storybook:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins

## Logs

```
info => Using implicit CSS loaders
(node:2584) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
/home/runner/work/documentation/documentation/submodules/volto/node_modules/razzle/config/env.js:78
    if (!options.forceRuntimeEnvVars.includes(key) || is_dev) {
                                     ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at /home/runner/work/documentation/documentation/submodules/volto/node_modules/razzle/config/env.js:78:38
    at Array.reduce (<anonymous>)
    at getClientEnvironment (/home/runner/work/documentation/documentation/submodules/volto/node_modules/razzle/config/env.js:77:40)
    at /home/runner/work/documentation/documentation/submodules/volto/node_modules/razzle/config/createConfigAsync.js:122:20
    at new Promise (<anonymous>)
    at module.exports (/home/runner/work/documentation/documentation/submodules/volto/node_modules/razzle/config/createConfigAsync.js:78:10)
    at Object.webpackFinal (/home/runner/work/documentation/documentation/submodules/volto/.storybook/main.js:44:24)
    at /home/runner/work/documentation/documentation/submodules/volto/node_modules/@storybook/core-common/dist/cjs/presets.js:274:28
    at async Object.webpack (/home/runner/work/documentation/documentation/submodules/volto/node_modules/@storybook/builder-webpack4/dist/cjs/presets/custom-webpack-preset.js:36:28)
    at async Object.build (/home/runner/work/documentation/documentation/submodules/volto/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:178:16)
    at async Promise.all (index 1)
    at async buildStaticStandalone (/home/runner/work/documentation/documentation/submodules/volto/node_modules/@storybook/core-server/dist/cjs/build-static.js:141:28)
    at async buildStatic (/home/runner/work/documentation/documentation/submodules/volto/node_modules/@storybook/core-server/dist/cjs/build-static.js:161:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/***/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by stevepiercy** [comment]
Fixed by https://github.com/plone/volto/pull/3689. We have [`plone/documentation` building successfully again](https://github.com/plone/documentation/actions/runs/3143777141/jobs/5108927332). Thank you!
