### ISSUE TITLE
@SaiRev0 it looks like this error happens when the package name starts with `volto`. I also saw this error:

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4440]
@SaiRev0 it looks like this error happens when the package name starts with `volto`. I also saw this error:

```
/tmp/voltonew$ yarn start
Internal Error: voltonew@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at OR.getCandidates (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:435:5209)
    at Bd.getCandidates (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:391:1281)
    at /tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:439:7764
    at Tg (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:390:11154)
    at ce (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:439:7744)
```

Really in this situation, when running `yarn install`, it starts to work.

The generator is located at:

https://github.com/plone/volto/tree/master/packages/generator-volto

_Originally posted by @wesleybl in https://github.com/plone/training/issues/715#issuecomment-1448126874_

**Comment by wesleybl** [comment]
@SaiRev0 I don't know what causes this error, but it may be related to: #3770 

CC @tiberiuichim

**Comment by stevepiercy** [comment]
When this issue is resolved, we need to remove the note in https://github.com/plone/training/pull/721
