### ISSUE TITLE
SearchDetails component is not properly rendered in SSR

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4612]
The output is like: `Searched for: <em>sometext</em>. Search results:`

This is because we're using react-intl 3.8 and https://github.com/vercel/next.js/issues/10533

**Comment by tiberiuichim** [comment]
There's an error in server console:

```
[React Intl] Error formatting message: "Searched for: <em>{searchedtext}</em>." for locale: "en", using default message as fallback.
Cannot format XML message without DOMParser
    at new FormatError (/mnt/docker/work/volto/node_modules/intl-messageformat/dist/formatters.js:27:28)
    at Object.formatHTMLMessage (/mnt/docker/work/volto/node_modules/intl-messageformat/dist/formatters.js:283:15)
    at IntlMessageFormat.formatHTMLMessage (/mnt/docker/work/volto/node_modules/intl-messageformat/dist/core.js:70:33)
    at formatMessage (/mnt/docker/work/volto/node_modules/react-intl/dist/formatters/message.js:66:47)
    at Object.children (/mnt/docker/work/volto/node_modules/react-intl/dist/components/message.js:73:25)
    at ReactDOMServerRenderer.render (/mnt/docker/work/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
    at ReactDOMServerRenderer.read (/mnt/docker/work/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/mnt/docker/work/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at /mnt/docker/work/volto/@plone/volto/src/server.jsx:246:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[React Intl] Error formatting the default message for: "Searched for: <em>{searchedtext}</em>."

```

**Comment by Suraj-Dhankad2025** [comment]
@tiberiuichim Please assign me the issue i want to contribute to it.

**Comment by tiberiuichim** [comment]
@Suraj-Dhankad2025 what's the plan? How do you plan to solve this issue?

**Comment by stevepiercy** [comment]
@Suraj-Dhankad2025 please see Volto and general contributing guidelines.

- https://6.docs.plone.org/volto/developer-guidelines/contributing.html
- https://6.docs.plone.org/contributing/index.html#making-contributions-on-github

**Comment by tiberiuichim** [comment]
I've just realised that the listing part of the search block is not yet made compatible with the SSR.

@plone/volto-team do we want SSR for the search block? My inclination is to say no, I don't see the value, if you rely on it for search engines, it's better to simply expose your content in sitemap.xml.gz. Maybe it makes a difference with accesibility, but I doubt it.

**Comment by davisagli** [comment]
I would agree, no SSR for the search block. It could hurt SEO for the actual pages if the search block is indexed including the same content.

**Comment by djay** [comment]
@davisagli @tiberiuichim the reason search needs to SSR is to start fixing progressive enhancement for search. I think we can agree that search is a basic service that should work without js?
https://www.gov.uk/service-manual/technology/using-progressive-enhancement

**Comment by davisagli** [comment]
@djay I had in mind that SEO is the main reason we render things on the server side in volto, but that does makes sense as a reason to want a server-rendered search page that is unrelated to SEO.

> Also the search page really shouldn't list anything until there is a search term IMO

Depends on the use case, whether it's more appropriate to start from 0 and add things, or filter down a list.

**Comment by djay** [comment]
@davisagli yes it depends. It should really be an option in the block settings. 
I'm just mentioning it because maybe it makes it easier to SSR with no results? As long as it then allows search with no J's there is still function

**Comment by tiberiuichim** [comment]
> It should really be an option in the block settings.

Indeed, we need it as an option. In the EEA Semantic Search we have that option, not to directly load any results.

Actually, there we have even more options, for example the ability to insert blocks inside the search block.

Sorry for my uncaffeinated brain, here's a short demo of what we have there (sound up, I've also recorded my voice).


https://user-images.githubusercontent.com/141568/229046967-690a9cca-88d7-4810-83e4-4c2fae6bc3b5.mp4

**Comment by JeffersonBledsoe** [comment]
Another thing to think about with disabling SSR for SEO purposes is search engine indexers ever-improving ability to run client-side JavaScript, we may not see the effects we want even if we did disable SSR (I'm no SEO expert, do let me know if I'm wrong here!)
