### ISSUE TITLE
yo @plone/volto fails

### ISSUE THREAD

**Issue by ksuess** [plone/volto#4734]
```
Getting latest Volto version
Using latest released Volto version: 16.20.4
Retrieving Volto's yarn.lock
? Project name (e.g. my-volto-project) scratch_volto-searchkit-block
? Would you like to add addons? false
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/katjasuss/Desktop/_temp/scratch_volto-searchkit-block/package.json.tpl'
    at Object.readdirSync (node:fs:1452:3)
    at exports.readdir (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/Users/katjasuss/.nvm/versions/node/v18.15.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/katjasuss/Desktop/_temp/scratch_volto-searchkit-block/package.json.tpl'
}
```

**Comment by davisagli** [comment]
@ksuess It is working for me with Node 18 and @plone/generator-volto@7.0.0-alpha.4. What version of @plone/generator-volto do you have installed?

**Comment by ksuess** [comment]
A new Volto project with version 17 alpha-xy can be generated with
- node 18
- `npm install -g @plone/generator-volto@alpha`
- `yo @plone/volto --canary`

Thank you for the hint with the generator version, @davisagli!
