### ISSUE TITLE
package.json.tbl not found when installing

### ISSUE THREAD

**Issue by dasmikko** [plone/volto#4817]
**Describe the bug**
Cannot install Plone 6 with Volto

**To Reproduce**
Following the guide from: 
https://6.docs.plone.org/install/install-from-packages.html

I get the following error when installing plone on Oracle Linux 9

I'm using Node 18 lts
python 3.9.16
yarn 3.5.1

```
[plone@localhost ploneinstall]$ cookiecutter https://github.com/collective/cookiecutter-plone-starter
You've downloaded /home/plone/.cookiecutters/cookiecutter-plone-starter before. Is it okay to delete and re-download it? [yes]: 
project_title [Project Title]: 
project_slug [project-title]: 
description [A new project using Plone 6.]: 
author [Plone Foundation]: 
email [collective@plone.org]: 
python_package_name [project_title]: 
Select python_test_framework:
1 - pytest
2 - unittest
Choose from 1, 2 [1]: 
plone_version [6.0.4]: 
volto_version [16.20.7]: 
volto_generator_version [6.3.1]: 
Select language_code:
1 - en
2 - de
3 - es
4 - pt-br
Choose from 1, 2, 3, 4 [1]: 
github_organization [collective]: 
Select container_registry:
1 - GitHub
2 - Docker Hub
Choose from 1, 2 [1]: 
================================================================================
Project Title generation
================================================================================
Running sanity checks
  - Python: ✓
  - Node: ✓
  - yo: ✓
  - Docker: ✓
  - git: ✓

Summary:
  - Plone version: 6.0.4
  - Volto version: 16.20.7
  - Volto Generator version: 6.3.1
  - Output folder: /home/plone/ploneinstall/project-title

Frontend codebase:
 - Installing @plone/generator-volto@6.3.1
 - Generate frontend application with @plone/volto 16.20.7

Error while running yo @plone/volto frontend --description 'A new project using Plone 6.' --addon @eeacms/volto-accordion-block --addon @kitconcept/volto-blocks-grid --addon @kitconcept/volto-slider-block --addon @eeacms/volto-matomo --skip-install --no-interactive --volto=16.20.7:
Using chosen Volto version: 16.20.7
Retrieving Volto's yarn.lock
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/home/plone/ploneinstall/project-title/frontend/package.json.tpl'
    at Object.readdirSync (node:fs:1452:3)
    at exports.readdir (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/home/plone/.nvm/versions/node/v18.16.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/plone/ploneinstall/project-title/frontend/package.json.tpl'
}

Node.js v18.16.0


ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Expected behavior**
It would install

**Software (please complete the following information):**

- OS: Oracle Linux 9
- Volto Version: 16.20.7
- Plone Version 6.0.4

**Comment by davisagli** [comment]
@dasmikko Volto 16 does not support Node 18.

> Oh and same issue with node 16

Can you show the output from when you tried with Node 16? The details may be helpful.

**Comment by dasmikko** [comment]
You are absolutely right. i installed node 16 and found out my yarn install was borked. 

After that, it installed fine. :)
