### ISSUE TITLE
Test backend build broken when using Plone 5.2.14 and the latest p.restapi

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#5218]
**Describe the bug**
The build of the test backend with Plone 5.2.14 image is broken:

**To Reproduce**

1. in `Makefile` update the version of plone.restapi used by the 5 series tests to use `5.2.14`
2. Run `make start-test-acceptance-server-5`
3. See error:
https://github.com/plone/volto/actions/runs/6264736158/job/17012091181?pr=5213

```
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 575, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/app/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    would_be_installed = _simulate_installation_of(to_install, package_set)
  File "/app/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 131, in _simulate_installation_of
    dist = abstract_dist.get_metadata_distribution()
  File "/app/lib/python3.8/site-packages/pip/_internal/distributions/wheel.py", line 23, in get_metadata_distribution
    assert self.req.local_file_path, "Set as part of preparation during download"
AssertionError: Set as part of preparation during download
Installing collected packages: plone.rest, plone.restapi, plone.volto, babel, plone.testing, plone.app.testing, robotframework, sortedcontainers, outcome, sniffio, exceptiongroup, trio, h11, wsproto, trio-websocket, selenium, robotframework-pythonlibcore, robotframework-seleniumlibrary, robotframework-selenium2library, orderedmultidict, furl, wrapt, robotframework-seleniumtestability, robotsuite, zope.testrunner, plone.app.robotframework, PySocks
  Attempting uninstall: plone.rest
    Found existing installation: plone.rest 1.6.2
    Uninstalling plone.rest-1.6.2:
      Successfully uninstalled plone.rest-1.6.2
  Attempting uninstall: plone.restapi
    Found existing installation: plone.restapi 7.8.3
    Uninstalling plone.restapi-7.8.3:
      Successfully uninstalled plone.restapi-7.8.3
  Rolling back uninstall of plone.restapi
  Moving to /app/lib/python3.8/site-packages/plone.restapi-7.8.3-py3.8-nspkg.pth
   from /tmp/pip-uninstall-mkanb42a/plone.restapi-7.8.3-py3.8-nspkg.pth
  Moving to /app/lib/python3.8/site-packages/plone.restapi-7.8.3.dist-info/
   from /app/lib/python3.8/site-packages/~lone.restapi-7.8.3.dist-info
  Moving to /app/lib/python3.8/site-packages/plone/restapi/
   from /app/lib/python3.8/site-packages/plone/~estapi
ERROR: Exception:
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/app/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/app/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 452, in run
    installed = install_given_reqs(
  File "/app/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/app/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 805, in install
    assert self.local_file_path
AssertionError
```

**Expected behavior**
It would not break

**Comment by ichim-david** [comment]
@ericof @sneridagh there is something funky going on with the test backend 
![test-backend-output](https://github.com/plone/volto/assets/152852/aa1ded4a-a047-4aad-a240-1c7920812749)
You don't get any ready flag, just an error that plone.app.event is already added.
You get some info about the backend only when you ctrl + c as seen in my screenshot.

Going to http://localhost:55001/ will show you a lovely we're sorry message
![were-sorry](https://github.com/plone/volto/assets/152852/11459849-aa7e-4df4-bfc4-8a4742f9479e)

and this is all felt with the latest volto main branch using the documented information for running acceptance tests
https://6.docs.plone.org/volto/contributing/acceptance-tests.html#how-to-run-acceptance-tests-locally-during-development

I barely managed to fumble my way around, I don't know how other beginners would know what to do if they were
tasks to write cypress tests and run them.

**Comment by davisagli** [comment]
@ichim-david That is a different problem from the one that was originally reported here. Could you please report it in a separate issue?

The message about plone.app.event is annoying but is not a real problem, which I guess is why no one has worked on it yet.

Zope is running even though it doesn't print the message saying so. We probably need to fix the logging configuration that is set up by the robot runner script.

**Comment by ichim-david** [comment]
> @ichim-david That is a different problem from the one that was originally reported here. Could you please report it in a separate issue?
> 
> The message about plone.app.event is annoying but is not a real problem, which I guess is why no one has worked on it yet.
> 
> Zope is running even though it doesn't print the message saying so. We probably need to fix the logging configuration that is set up by the robot runner script.

@davisagli added https://github.com/plone/volto/issues/5691 , maybe your comment from here would be good to have on this issue that I've added per your suggestion.
