### ISSUE TITLE
Volto generator not compatible with node 18

### ISSUE THREAD

**Issue by jackahl** [plone/volto#5228]
**Describe the bug**
When using Node Version 18 generating a new Volto Project with latest Volto Alpha Verison.

**To Reproduce**

1. Switch to Node 18 using `nvm use 18`
2. run the Volto Generator in canary mode using `yo @plone/volto --canary`
3. Enter a project name and dont install any addons
4. Error

```
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/jakobkahl/workspace/my-new-volto-alpha-project/package.json.tpl'
    at Object.readdirSync (node:fs:1527:3)
    at exports.readdir (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:507:12)
    at readdirSync (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/Users/jakobkahl/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/jakobkahl/workspace/my-new-volto-alpha-project/package.json.tpl'
}

Node.js v18.18.0
```

**Expected behavior**
A new Volto Project should be created.

**Software (please complete the following information):**

- OS: macOS 13.4 (22F66) (M1 and Intel Chip)
- Volto 17.0.0-alpha.27 (2023-09-18)

**Additional context**

**Comment by sneridagh** [comment]
@jackahl I just tested out:

```
npm -g i @plone/generator-volto@alpha
yo @plone/volto my-volto-app --description "test volto project" --skip-install --no-interactive --canary
```

With Node 18.17.1 and it worked. Could be that you are using the non alpha version of the generator?

**Comment by claudiaifrim** [comment]
> @jackahl I just tested out:
> 
> ```
> npm -g i @plone/generator-volto@alpha
> yo @plone/volto my-volto-app --description "test volto project" --skip-install --no-interactive --canary
> ```
> 
> With Node 18.17.1 and it worked. Could be that you are using the non alpha version of the generator?

Yes, it's the error when installing the non alpha version.

```
npm install -g @plone/generator-volto
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@plone/generator-volto@6.3.1',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.18.0', npm: '9.8.1' }
npm WARN EBADENGINE }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
```

```
claudia@claudia-ThinkPad-T470p ~/work/sources/volto $ yo @plone/volto volto-weather-block
Getting latest Volto version
Using latest released Volto version: 16.24.0
Retrieving Volto's yarn.lock
? Would you like to add addons? false
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/home/claudia/work/sources/volto/volto-weather-block/package.json.tpl'
    at Object.readdirSync (node:fs:1527:3)
    at exports.readdir (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:507:12)
    at readdirSync (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/home/claudia/.nvm/versions/node/v18.18.0/lib/node_modules/@plone/generator-volto/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/claudia/work/sources/volto/volto-weather-block/package.json.tpl'
}
Node.js v18.18.0
claudia@claudia-ThinkPad-T470p ~/work/sources/volto $ node --version
v18.18.0
```

**Comment by jackahl** [comment]
@sneridagh @claudiaifrim thanks for clarifying. Closing

**Comment by sneridagh** [comment]
Reopening, we should be able to run it in 18, since we added support for it in Volto 16.

**Comment by sneridagh** [comment]
I made a PR, let's see if that works.

**Comment by sneridagh** [comment]
@jackahl @claudiaifrim Please test the latest generator (6.4.0) with the latest fixes. Worked for me locally.

https://www.npmjs.com/package/@plone/generator-volto

```
npm -g i @plone/generator-volto
yo @plone/volto my-volto-app --description "test volto project" --skip-install --no-interactive
```

**Comment by sneridagh** [comment]
Closing, feel free to reopen if you test it and it's not right.
