### ISSUE TITLE
moment-locales-webpack-plugin missing from new project with Volto 17.0.0-alpha.28

### ISSUE THREAD

**Issue by pbauer** [plone/volto#5237]
**Describe the bug**
Startup of a new Volto project fails

**To Reproduce**

1. I create a new project using `yo @plone/volto --canary`
2. `yarn install`
3. `yarn start`

```
 ERROR  Invalid razzle.config.js file.

Error: Cannot find module 'moment-locales-webpack-plugin'
Require stack:
- /Users/pbauer/workspace/ipn/ipn-frontend/node_modules/@plone/volto/razzle.config.js
- /Users/pbauer/workspace/ipn/ipn-frontend/razzle.config.js
- /Users/pbauer/workspace/ipn/ipn-frontend/node_modules/razzle/config/loadRazzleConfig.js
- /Users/pbauer/workspace/ipn/ipn-frontend/node_modules/razzle/scripts/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/@plone/volto/razzle.config.js:16:29)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/pbauer/workspace/ipn/ipn-frontend/razzle.config.js:22:34)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/@plone/volto/razzle.config.js',
    '/Users/pbauer/workspace/ipn/ipn-frontend/razzle.config.js',
    '/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/razzle/config/loadRazzleConfig.js',
    '/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/razzle/scripts/start.js'
  ]
}
```

When I add `"moment-locales-webpack-plugin": "1.2.0",` to my `package.json` the error goes away.

**Comment by pbauer** [comment]
Fixed by https://github.com/plone/volto/pull/5236
