### ISSUE TITLE
Missing stylelint dependency: stylelint-config-prettier

### ISSUE THREAD

**Issue by pbauer** [plone/volto#5242]
**To Reproduce**

1. Install newest generator `npm install -g @plone/generator-volto@7.0.0-alpha.10`
2. Create Project with Volto 17.0.0-alpha.30 `yo @plone/volto --canary`
3. Run `yarn stylelint`

```
Error: Could not find "stylelint-config-prettier". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/augmentConfig.js:216:21)
    at extendConfig (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/augmentConfig.js:184:25)
    at augmentConfigBasic (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/augmentConfig.js:57:26)
    at augmentConfigFull (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/augmentConfig.js:111:30)
    at Object.transform (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/getConfigForFile.js:51:37)
    at search (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:47:54)
    at async Explorer.search (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:71:20)
    at async getConfigForFile (/Users/pbauer/workspace/ipn/ipn-frontend/node_modules/stylelint/lib/getConfigForFile.js:62:5)
```

**Comment by pbauer** [comment]
Fixed with https://github.com/plone/volto/pull/5243
