### ISSUE TITLE
Frontend image build fails with volto-generator 8.0.3 but not 8.0.2 or before

### ISSUE THREAD

**Issue by kenmanheimer** [plone/volto#5454]
**Describe the bug**
When I try to build a Plone + Volto instance using cookiecutter with Volto Generator version 8.0.3 and whatever versions of Plone and Volto and no changes to the generated code, the build fails with the error below. If I use Volto Generator 8.0.2 and whatever versions of Plone and Volto the build succeeds. This problem happens on the two completely separate build hosts. It was happening a few days ago and I just tried again (in case the Volto Generator version was incremented or the broken version was fixed) and it's still happening.

**To Reproduce**

1. `cookiecutter https://github.com/collective/cookiecutter-plone-starter`
2. `cd <instance> && make install && cd frontend && make build-image`
4. See error:

```
ERROR  Unexpected error

Error: ENOENT: no such file or directory, lstat
'/bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/@plone/volto/packages/registry'
    at Object.realpathSync (node:fs:2533:7)
    at /bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/@plone/volto/razzle.config.js:284:20
    at Array.forEach (<anonymous>)
    at defaultModify (/bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/@plone/volto/razzle.config.js:283:19)
    at modifyWebpackConfig
(/bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/@plone/volto/razzle.config.js:378:27)
    at customModifyWebpackConfig (/bulk/klm/Servers/Myr/myriadicity-net/frontend/razzle.config.js:31:18)
    at /bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/razzle/config/createConfigAsync.js:1069:22 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/bulk/klm/Servers/Myr/myriadicity-net/frontend/node_modules/@plone/volto/packages/registry'
}
```

**Software (please complete the following information):**

- OS: [e.g. iOS]: Ubuntu Linux 20.04, Ubuntu Linux 22.04
- Volto Version: 17.6.1, 17.6.0, 17.5.0
- Plone Version: 6.0.8, 6.0.7

**Workaround**

I can workaround this using Volto Generator 8.0.2 but I don't know what is lost doing that.

**Comment by kenmanheimer** [comment]
Thanks, Volto Generator 8.1.0 works for me with the most recent Volto release.
