### ISSUE TITLE
make backend-docker-start fails with ('en_US:en', 'value') error

### ISSUE THREAD

**Issue by avoinea** [plone/volto#6404]
**Describe the bug**
```
Traceback (most recent call last):
  File "/app/bin/zconsole", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/Zope2/utilities/zconsole.py", line 50, in main
    runscript(namespace.zopeconf, *namespace.scriptargs)
  File "/app/lib/python3.11/site-packages/Zope2/utilities/zconsole.py", line 22, in runscript
    exec(compile(scriptcode, script_name, 'exec'), scriptglobals)
  File "/app/scripts/create_site.py", line 84, in <module>
    site = addPloneSite(app, SITE_ID, **payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Products/CMFPlone/factory.py", line 170, in addPloneSite
    reg["plone.default_language"] = default_language
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/plone/registry/registry.py", line 45, in __setitem__
    self.records[name].value = value
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/plone/registry/record.py", line 79, in _set_value
    field.validate(value)
  File "/app/lib/python3.11/site-packages/zope/schema/_bootstrapfields.py", line 295, in validate
    self._validate(value)
  File "/app/lib/python3.11/site-packages/zope/schema/_field.py", line 475, in _validate
    raise ConstraintNotSatisfied(
zope.schema._bootstrapinterfaces.ConstraintNotSatisfied: ('en_US:en', 'value')
make[1]: *** [Makefile:110: backend-docker-start] Error 1
make[1]: Leaving directory '/opt/sandbox/volto/packages/volto'
```

**To Reproduce**
```
git clone git@github.com:plone/volto.git
cd volto
pnpm install
make backend-docker-start
```
**Software (please complete the following information):**

- OS: Ubuntu 22.04
- Volto Version latest
- Plone Version latest
- Plone REST API Version latest

**Comment by aadityaforwork** [comment]
I did try to reproduce but the command make backend-docker-start gets successfully executed is there anything more specific to reproduce @avoinea ?

**Comment by davisagli** [comment]
@avoinea Do you have the LANGUAGE environment variable set? It should default to using `en`, not `en_US:en`: https://github.com/plone/plone-backend/blob/6.0.x/skeleton/scripts/create_site.py#L38

**Comment by avoinea** [comment]
@davisagli Yap. That's it! Not sure how it ended up there :smile: 
```
$ env | grep LANGUAGE
LANGUAGE=en_US:en
```

**Comment by wesleybl** [comment]
> Do you have the LANGUAGE environment variable set? It should default to using en, not en_US:en: https://github.com/plone/plone-backend/blob/6.0.x/skeleton/scripts/create_site.py#L38

@davisagli I had this same problem:

```
raise ConstraintNotSatisfied(
zope.schema._bootstrapinterfaces.ConstraintNotSatisfied: ('pt_BR:pt:en', 'value')
```

But I wouldn't like to change this environment variable. I think the code should handle this situation.

And users with this problem may take a while to find the solution.

**Comment by wesleybl** [comment]
In my case, it only worked with `LANGUAGE=pt-br`. `pt_BR`, which was in the variable, did not work. Should the code do this conversion?

**Comment by wesleybl** [comment]
Maybe another variable should be used, not `LANGUAGE`.

**Comment by davisagli** [comment]
@wesleybl We weren't intending to use an environment variable that is already set for other purposes. We need to either convert it or switch to use a different environment variable.

**Comment by wesleybl** [comment]
@davisagli I created a PR: https://github.com/plone/plone-backend/pull/170

**Comment by wesleybl** [comment]
This has been fixed in https://github.com/plone/plone-backend/pull/170 and https://github.com/plone/plone-backend/pull/181. Waiting for Plone release 6.1.1 to take effect. See: https://github.com/plone/volto/issues/6747.
