### ISSUE TITLE
Error ImageZoom: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by TBCcrash2064** [plone/volto#823]
Got error while starting volto:
`TypeError: Cannot read property 'startsWith' of undefined

  29 |     <ImageZoom
  30 |       image={{
> 31 |         src: data.url.startsWith(settings.apiPath)
  32 |           ? `${flattenToAppURL(data.url)}/@@images/image`
  33 |           : data.url,
  34 |         alt: '',

    at View (/Applications/Plone/installertest/volto/src/components/manage/Tiles/Image/View.jsx:31:1)
    at processChild (/Applications/Plone/installertest/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Applications/Plone/installertest/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Applications/Plone/installertest/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Applications/Plone/installertest/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Applications/Plone/installertest/volto/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at /Applications/Plone/installertest/volto/build/webpack:/src/server.jsx:106:1
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I think, this is a new function from the commit "image-zoom added" in march?

**Comment by TBCcrash2064** [comment]
Oha.. sorry. Totally my fault
