### ISSUE TITLE
ERROR:ZODB.Connection:Shouldn't load state for Products.CMFCore.ActionInformation.Action

### ISSUE THREAD

**Issue by tisto** [plone/volto#969]
I ran into this error trace during Cypress tests and during prod as well:

````
ERROR:ZODB.Connection:Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
Traceback (most recent call last):
  File "/home/travis/buildout-cache/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 785, in setstate
    raise ConnectionStateError(msg)
ZODB.POSException.ConnectionStateError: Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
ERROR:ZODB.Connection:Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
Traceback (most recent call last):
  File "/home/travis/buildout-cache/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 785, in setstate
    raise ConnectionStateError(msg)
ZODB.POSException.ConnectionStateError: Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
ERROR:ZODB.Connection:Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
Traceback (most recent call last):
  File "/home/travis/buildout-cache/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 785, in setstate
    raise ConnectionStateError(msg)
ZODB.POSException.ConnectionStateError: Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
ERROR:ZODB.Connection:Shouldn't load state for Products.CMFCore.ActionInformation.Action 0x17c303e488cf2401 when the connection is closed
Traceback (most recent call last):
  File "/home/travis/buildout-cache/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 785, in setstate
    raise ConnectionStateError(msg)
````

Source: https://travis-ci.org/plone/volto/jobs/604362998?utm_medium=notification&utm_source=email

This requires further investigation. I add this here as a starting point.

**Comment by pnicolli** [comment]
Something similar happened here as well: https://travis-ci.org/plone/volto/jobs/604329404

**Comment by sneridagh** [comment]
It's been a while that I haven't seen it. I think we finally obliterate the bug thanks to @datakurre when he took a look at the order of the layer teardown some time ago. Closing for now!
